apps/authentication/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name = 'authentication'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

main_conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('apps.customer.urls')),
    path('data-processing/', include('apps.process_data.urls')),
    path('auth/', include('apps.authentication.urls', namespace='authentication')),
    path('app/', include('apps.app.urls', namespace='app')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_r=settings.STATIC_ROOT)

templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a target="_blank"
                                       href="https://appseed.us/admin-dashboards/django-dashboard-volt">Django Volt</a> - Sign IN
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p>    
                            </div>

                            <form method="post" action="" class="mt-4">
                                
                                {% csrf_token %} 

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user-circle"></span></span>
                                        {{ form.username }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                                            <label class="form-check-label" for="defaultCheck5">
                                              Remember me
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <a href="{% url 'authentication:register' %}" class="small text-right">Register</a>
                                        </div>
                                    </div>

                                </div>
                                <button type="submit" name="login" class="btn btn-block btn-primary">Sign in</button>
                            </form>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="font-weight-normal">
                                    &copy; <a  href="https://themesberg.com" target="_blank">Themesberg</a> 
                                    - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a target="_blank"
                                       href="https://appseed.us/admin-dashboards/django-dashboard-volt">Django Volt</a> - Sign UP
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p>    
                            </div>
                            
                            <form method="post" action="">
                            
                                {% csrf_token %}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-user-shield"></span></span>
                                        {{ form.username }}
                                    </div>
                                    <span class="text-error">{{ form.username.errors }}</span>
                                </div>
                                <!-- End of Form -->

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Your Email</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                        {{ form.email }}
                                    </div>
                                    <span class="text-error">{{ form.email.errors }}</span>
                                </div>
                                <!-- End of Form -->

                                <div class="form-group">

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password1 }}
                                        </div>  
                                        <span class="text-error">{{ form.password1.errors }}</span>
                                    </div>
                                    <!-- End of Form -->

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Password Check</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password2 }}
                                        </div>  
                                        <span class="text-error">{{ form.password2.errors }}</span>
                                    </div>

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                                            <label class="form-check-label" for="defaultCheck5">
                                              Agree terms
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <a href="{% url 'authentication:login' %}" class="small text-right">Login</a>
                                        </div>
                                    </div>
                                    
                                </div>
                                <button type="submit" name="register" class="btn btn-block btn-primary">Sign in</button>
                            </form>
                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="font-weight-normal">
                                    &copy; <a  href="https://themesberg.com" target="_blank">Themesberg</a> 
                                    - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}