apps/customer/urls.py
from django.urls import path
from . import views
from apps.process_data.views import raw_upload_data

app_name = "customer"

urlpatterns = [
    path("dme_raw", views.uploadlist_dme, name="dme_list"),
    path('view/<int:object_id>/', views.view_uploaded_object, name= 'view_uploaded_object'),
    path('download_object/<int:id>/', views.download_object, name='download_object'),
    path("raw_kaon", views.uploadlist_kaon, name= 'kaon_list'),
    path('raw_path_rout/', raw_upload_data, name='raw_data_rout'),

    #path("<int:pk>/", views.customer_detail, name="detail"),
    #path("create/", views.customer_create, name="create"),
]

apps/process_data/urls.py
from django.urls import path
from . import views
# from . import data_table
 
app_name = 'processing_data'

urlpatterns = [
    
    #production directories
    path('process-data/lg/', views.process_data, name='process_data'),
    path('process-data/dme/', views.process_data_dme, name = 'process_dme'),
    path('process-data/dme-bom/', views.upload_bom_file, name = 'process_dme_bom'),
    path('process-data/kaon/',views.process_data_kaon, name='process_kaon'),
    path('process-data/landis/',views.process_data_landis, name='process_landis'),
    path('process-data/dme/dir', views.process_data_page_dme,name='process_dme_dir'),
    path('process-data-page/', views.process_data_page, name='process_data_page'),
    path('objects/', views.list_objects, name='list_objects'),
    path('objects/dme/', views.list_objects_dme, name='list_objects_dme'),
  
  
    #Raw data 
    path('view_object_dme/<int:id>/', views.list_objects_dme, name='raw_view_object_dme'),
    path('download_object/<int:id>/', views.raw_download_object, name='raw_download_object'),
    path('delete_object/<int:id>/', views.raw_delete_object, name='raw_delete_object'),
    path('edit_object/<int:id>/', views.raw_edit_object, name='raw_edit_object'),
    path('raw_path_rout/',views.raw_upload_data, name='raw_data_rout'),

    #processed data 
    path('data-processing/objects/list', views.processed_data_route, name='processed_data_route'),
    path('download/<int:object_id>/', views.download_object, name='download_object'),
    path('edit/<int:object_id>/', views.edit_object, name='edit_object'),
    path('delete/<int:object_id>/', views.delete_object, name='delete_object'),
    path('objects/<int:object_id>/', views.view_object, name='view_object'),
    path('objects-dme/<int:object_id>',views.view_object_dme, name='view_object_dme'),
]

main_conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('apps.customer.urls')),
    path('data-processing/', include('apps.process_data.urls')),
    path('auth/', include('apps.authentication.urls', namespace='authentication')),
    path('app/', include('apps.app.urls', namespace='app')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_r=settings.STATIC_ROOT)

apps/process_data/forms.py
# forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit


class UploadDataForm(forms.Form):
    dirty_txt_file = forms.FileField(
        label='Upload Text File (.txt)',
        help_text='Select a Text file to upload (.txt format)',
        widget=forms.ClearableFileInput(attrs={'accept': '.txt'}),
    )

    dirty_excel_file = forms.FileField(
        label='Upload Excel File (.xlsx)',
        help_text='Select an Excel file to upload (.xlsx format)',
        widget=forms.ClearableFileInput(attrs={'accept': '.xlsx'}),
    )

    helper = FormHelper()
    helper.form_method = 'post'
    helper.form_class = 'form-horizontal'
    helper.add_input(Submit('submit', 'Process Data'))





class UploadDataForm2(forms.Form):
    dirty_html = forms.FileField(
        label='Upload Htm File (.htm/.html)',
        help_text='Select an Htm file to upload (.htm/.html format)',
        widget=forms.ClearableFileInput(attrs={'accept': '.htm,.html'})
    )
    dirty_excel_file = forms.FileField(
        label='Upload Excel File (.xlsx)',
        help_text='Select an Excel file to upload (.xlsx format)',
        widget=forms.ClearableFileInput(attrs={'accept': '.xlsx'})
    )

    helper = FormHelper()
    helper.form_method = 'post'
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Field('dirty_html'),
        Field('dirty_excel_file'),
        Submit('submit', 'Process Data')
    )


class UploadBomDataForm(forms.Form):
    dirty_excel_file = forms.FileField(
        label='Upload Excel File (.xlsx)',
        help_text='Select an Excel file to upload (.xlsx format)',
        widget=forms.ClearableFileInput(attrs={'accept': '.xlsx'}),
    )

    helper = FormHelper()
    helper.form_method = 'post'
    helper.form_class = 'form-horizontal'
    helper.add_input(Submit('submit', 'Process Data'))

apps/process_data/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from .data_processing import process_uploaded_files
from .forms import  UploadDataForm,UploadBomDataForm
from .forms import UploadDataForm2
from dash.exceptions import PreventUpdate
from .process_dme import process_data_and_merge
from .process_kaon import process_data_merge
from .process_landis import process_landis
from .bom_process_dme import process_xlsx_file_bom
import pandas as pd
from django.core.files import File
from . import models
import datetime
from django.http import FileResponse
import dash
from celery import shared_task
import base64
import io
from django.core.files.storage import default_storage
from django.shortcuts import get_object_or_404
from dash import dash_table
import pandas as pd
from django_plotly_dash import DjangoDash
from django.http import JsonResponse
import pandas as pd
from django.views.decorators.csrf import csrf_protect
import os
import dash as dcc
import dash_html_components as html
from dash import dash_table
from dash.dependencies import Input, Output,State
import pandas as pd
from dash.exceptions import PreventUpdate
import logging
from django.conf import settings
from django.contrib import messages



logger = logging.getLogger(__name__)



def process_data_page(request):
    return render(request, 'process_data_page.html')

def raw_upload_data(request):
    return render(request, 'raw_data_dir.html')

def process_data_page_dme(request):
    return render(request, 'dme/dme_dir.html')


def processed_data_route(request):
    return render(request, 'processed_list.html')

def list_objects(request):
    objects = models.ProcessedDataLG.objects.all()
    return render(request, 'transactions.html', {'objects': objects})


def list_uploaded_files(request):
    files = models.UploadedFileDME.objects.all()
    return render(request, 'uploaded_files.html', {'files': files})


@shared_task
def cleanup_nonexistent_files():
    all_objects = models.ProcessedDataDME.objects.all()
    for obj in all_objects:
        file_path = os.path.join(settings.MEDIA_ROOT, str(obj.processed_file))
        if not os.path.exists(file_path):
            obj.delete()

def list_objects_dme(request):
    all_objects = models.ProcessedDataDME.objects.all()
    existing_objects = []

    for obj in all_objects:
        file_path = os.path.join(settings.MEDIA_ROOT, str(obj.processed_file))
        if os.path.exists(file_path):
            existing_objects.append(obj)
        else:
            # Optionally, you can delete the database entry if the file doesn't exist
            obj.delete()

    return render(request, 'dme/transactions.html', {'objects': existing_objects})

def raw_download_object(request, object_id):
    if request.method == 'GET':
        object = get_object_or_404(models.UploadedFileDME, id=object_id)
        
        file_obj = object.processed_file.open()
        response = HttpResponse(file_obj.read(), content_type='application/force-download')
        response['Content-Disposition'] = f'attachment; filename={object.processed_file.name}'
        return response
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

def raw_edit_object(request, object_id):
    object = get_object_or_404(models.UploadedFileDME, id=object_id)
    if request.method == 'POST':
        new_name = request.POST.get('new_name')
        if not new_name:
            return JsonResponse({'success': False, 'error': 'No new name provided'})

        old_file_path = object.processed_file.name
        new_file_path = os.path.join(os.path.dirname(old_file_path), new_name)

        # Check if file with the new name already exists
        if default_storage.exists(new_file_path):
            return JsonResponse({'success': False, 'error': 'File with this name already exists'})

        # Save the file with the new name
        file_content = object.processed_file.file.read()
        default_storage.delete(old_file_path)
        default_storage.save(new_file_path, file_content)
        
        # Update the database record
        object.processed_file.name = new_file_path
        object.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return JsonResponse({'success': False, 'error': 'Invalid request method'})



def raw_delete_object(request, object_id):
    object = get_object_or_404(models.UploadedFileDME, id=object_id)
    
    if request.method == 'POST':
        default_storage.delete(object.processed_file.name)
        object.delete()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})







def download_object(request, object_id):
    if request.method == 'GET':
        object = get_object_or_404(models.ProcessedDataDME, id=object_id)
        
        file_obj = object.processed_file.open()
        response = HttpResponse(file_obj.read(), content_type='application/force-download')
        response['Content-Disposition'] = f'attachment; filename={object.processed_file.name}'
        return response
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

def edit_object(request, object_id):
    object = get_object_or_404(models.ProcessedDataDME, id=object_id)
    if request.method == 'POST':
        new_name = request.POST.get('new_name')
        if not new_name:
            return JsonResponse({'success': False, 'error': 'No new name provided'})

        old_file_path = object.processed_file.name
        new_file_path = os.path.join(os.path.dirname(old_file_path), new_name)

        # Check if file with the new name already exists
        if default_storage.exists(new_file_path):
            return JsonResponse({'success': False, 'error': 'File with this name already exists'})

        # Save the file with the new name
        file_content = object.processed_file.file.read()
        default_storage.delete(old_file_path)
        default_storage.save(new_file_path, file_content)
        
        # Update the database record
        object.processed_file.name = new_file_path
        object.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

def delete_object(request, object_id):
    object = get_object_or_404(models.ProcessedDataDME, id=object_id)
    
    if request.method == 'POST':
        default_storage.delete(object.processed_file.name)
        object.delete()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})

app = DjangoDash("DataTableApp")

def view_object(request, object_id):
    object = models.ProcessedDataLG.objects.get(id=object_id)
    df = pd.read_csv(object.processed_data.path)
    
    data_table_columns = [{'name': i, 'id': i} for i in df.columns]

    app.layout = html.Div([
        dash_table.DataTable(
        id='data-table',
        columns=data_table_columns,
        data=df.to_dict('records'),
        editable=True,
        row_deletable=True,
        sort_action="native",
        sort_mode="single",
        filter_action="native",
        page_action='none',
        style_table={'height': '1000px', 'overflowY': 'auto'},
        style_cell={'textAlign': 'left', 'minWidth': '100px', 'width': '300px', 'maxWidth': '300px'},
        style_header={
            'backgroundColor': 'rgb(230, 230, 230)',
            'fontWeight': 'bold'
        },
        style_data_conditional=[
            {
                'if': {'row_index': 'odd'},
                'backgroundColor': 'rgb(248, 248, 248)'
            }
        ]
    ),
])


    return render(request, 'data_table.html', {'object_id': object_id})







def view_object_dme(request, object_id):
    object = models.ProcessedDataDME.objects.get(id=object_id)
    original_df = pd.read_csv(object.processed_file.path)
    data_table_columns = [{'name': i, 'id': i} for i in original_df.columns]

    app.layout = html.Div([
        dash_table.DataTable(
            id='data-table',
            columns=data_table_columns,
            data=original_df.to_dict('records'),
            editable=True,
            row_deletable=True,
            sort_action="native",
            sort_mode="single",
            filter_action="native",
            page_action='none',
            style_table={'height': '600px', 'overflowY': 'auto', 'border': '1px solid #ddd', 'padding': '10px'},
            style_cell={'textAlign': 'left', 'padding': '10px', 'font-size': '14px'},
            style_header={'backgroundColor': '#f0f0f0', 'fontWeight': 'bold', 'color': '#333', 'border-bottom': '1px solid #ddd'},
            style_data_conditional=[
                {'if': {'row_index': 'odd'}, 'backgroundColor': '#f8f8f8'},
                {'if': {'column_id': 'Designator'}, 'minWidth': '100px', 'width': '150px', 'maxWidth': '150px'},
                {'if': {'column_id': 'Value'}, 'minWidth': '200px', 'width': '250px', 'maxWidth': '250px'},
                # Add more conditional styles for other columns as needed
            ]
        ),
        html.Div([
            html.Button("Save Changes", id="save-changes")
        ], style={'display': 'inline-block'})
    ])

    @app.callback(
        Output('data-table', 'data'),
        Input('save-changes', 'n_clicks'),
        State('data-table', 'data'),
        prevent_initial_call=True,
    )
    def save_changes(n_clicks, updated_data):
        if n_clicks is None:
            raise PreventUpdate
        updated_df = pd.DataFrame(updated_data)
        updated_df.to_csv(object.processed_file.path, index=False)
        return updated_data

    return render(request, 'data_table.html', {'object_id': object_id})


def view_object_dme(request, object_id):
    object = models.ProcessedDataDME.objects.get(id=object_id)
    original_df = pd.read_csv(object.processed_file.path)

templates/calendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Volt Premium Bootstrap Dashboard - Calendar</title>
    <link href="fullcalendar/main.css" rel="stylesheet" />
</head>
<body>
    <div id="calendar"></div>

    <!-- Include FullCalendar JS -->
    <script src="fullcalendar/main.js"></script>
    <!-- Include your custom JS file -->
    <script src="your_custom_script.js"></script>
</body>
</html>

<script>

    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        selectable: true,
        initialView: 'dayGridMonth',
        themeSystem: 'bootstrap',
        editable: true,
        events: [
            {% for data in processed_data %}
            {
                title: '{{ data.title }}',
                start: '{{ data.production_date }}',
                end: '{{ data.closing_date }}',
                className: 'bg-blue',
                dragabble: true
            },
            {% endfor %}
        ]
    });

    calendar.render();

</script>

templates/data_table.html
{% extends "layouts/base.html" %}

<style>
    .content {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding-top: 100px; /* Increased padding to 100px */
        font-size: 18px;
        font-family: Arial, sans-serif;
      }
    </style>

{% block title %} Processed files {% endblock %} 

<!-- Specific Page CSS goes HERE  -->


{% block content %}
    <main class="content">
        {% load plotly_dash %}
        <h3>Processed Data</h3>
        <div id="DataTableApp">
            {% plotly_app name='DataTableApp' ratio=1.75  %}
        </div>
        
    </main>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/lock.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Lock {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 bg-soft d-flex align-items-center my-4">
            <div class="container">
                <p class="text-center"><a href="../dashboard/dashboard.html" class="text-gray-700"><i class="fas fa-angle-left mr-2"></i> Back to homepage</a></p>
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow-soft border border-light rounded p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <div class="user-avatar large-avatar mx-auto mb-3 border-dark p-2"><img class="rounded-circle" alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg"></div>
                                <h1 class="mb-3 h3">Bonnie Green</h1>
                                <p class="text-gray">Better to be safe than sorry.</p>
                            </div>
                            <form class="mt-5">
                                <div class="mb-4">
                                    <label for="exampleInputPasswordCard4">Your Password</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><span class="fas fa-unlock-alt"></span></span>
                                        <input type="password" placeholder="Password" class="form-control" id="exampleInputPasswordCard4">
                                        <span class="input-group-text"><span class="far fa-eye"></span></span>
                                    </div>  
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-block btn-primary">Unlock</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 403 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-100 d-flex align-items-center justify-content-center">
            <div class="container">
                <div class="row align-items-center ">
                    <div class="col-12 col-lg-5 order-2 order-lg-1 text-center text-lg-left">
                        <h1 class="mt-5">Error 403</h1>
                        <p class="lead my-4">Access denied. Please authenticate or contact support.</p>
                        <a class="btn btn-primary animate-hover" href="/"><i class="fas fa-chevron-left mr-3 pl-2 animate-left-3"></i>Go back home</a>
                    </div>
                    <div class="col-12 col-lg-7 order-1 order-lg-2 text-center d-flex align-items-center justify-content-center">
                        <img class="img-fluid w-75" src="/static/assets/img/illustrations/500.svg" alt="500 Server Error">
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 404 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-100 d-flex align-items-center justify-content-center">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center d-flex align-items-center justify-content-center">
                        <div>
                            <img class="img-fluid w-75" src="/static/assets/img/illustrations/404.svg" alt="404 not found">
                            <h1 class="mt-5">Page not <span class="font-weight-bolder text-primary">found</span></h1>
                            <p class="lead my-4">Oops! Looks like you followed a bad link. If you think this is a
                                problem with us, please tell us.</p>
                            <a class="btn btn-primary animate-hover" href="/"><i class="fas fa-chevron-left mr-3 pl-2 animate-left-3"></i>Go back home</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/process_data_page.html
{% extends 'layouts/base.html' %}
{% include 'include/navigation.html' %}

<style>
    .content {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding-top: 100px; /* Increased padding to 100px */
        font-size: 18px;
        font-family: Arial, sans-serif;
      }
    </style>
{% block content %}
  <h2>Process Your Data Files</h2>
   <div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Process DME</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'processing_data:process_dme_dir' %}">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body"> Process Kaon</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'processing_data:process_kaon' %}">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Process Landis</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'processing_data:process_landis' %}">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Process The  </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'processing_data:process_data' %}">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
   {% include 'includes/scripts.html' %}
{% endblock %}
  
{% block footer %}

{% endblock %}

templates/processed_list.html
{% extends "layouts/base.html" %}

{% block title %} Processed files {% endblock %} 

{% include 'include/navigation.html' %}

{% block content %}
<h2>Process Your Data Files</h2>
<div class="row">
 <div class="col-xl-3 col-md-6">
     <div class="card bg-primary text-white mb-4">
         <div class="card-body">Processed DME CAD files</div>
         <div class="card-footer d-flex align-items-center justify-content-between">
             <a class="small text-white stretched-link" href="{% url 'processing_data:list_objects_dme' %}">View Details</a>
             <div class="small text-white"><i class="fas fa-angle-right"></i></div>
         </div>
     </div>
 </div>
 <div class="col-xl-3 col-md-6">
     <div class="card bg-warning text-white mb-4">
         <div class="card-body"> Process Demontrative</div>
         <div class="card-footer d-flex align-items-center justify-content-between">
             <a class="small text-white stretched-link" href="{% url 'processing_data:list_objects' %}">View Details</a>
             <div class="small text-white"><i class="fas fa-angle-right"></i></div>
         </div>
     </div>
{% endblock %}

{% block javascript %}
   {% include 'includes/scripts.html' %}
{% endblock %}
  
{% block footer %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 text-center">
            <p>&copy; 2023 Your Company</p>
        </div>
    </div>
</div>
{% endblock %}


 

templates/raw_data_dir.html
{% extends 'layouts/base.html' %}
{% include 'include/navigation.html' %}

<style>
    .content {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding-top: 100px; /* Increased padding to 100px */
        font-size: 18px;
        font-family: Arial, sans-serif;
      }
    </style>
{% block content %}
  <h2>Process Your Data Files</h2>
   <div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Raw data upload files DME</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{% url 'customer:dme_list' %}">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body"> Process Kaon</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="/">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Process Landis</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="/">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Process The  </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="/">View Details</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
   {% include 'includes/scripts.html' %}
{% endblock %}
  
{% block footer %}

{% endblock %}

templates/transactions.html
{% extends "layouts/base.html" %}

{% block title %} Processed files {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    <style>
        .content {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding-top: 20px; /* Add some top padding to create space */
            font-size: 18px; /* Adjust font size as needed */
            font-family: Arial, sans-serif; /* Choose an appropriate font family */
        }

        /* Add rounded borders to the table cells */
        table, th, td {
            border: 1px solid black;
            border-radius: 10px; /* Rounded corners */
        }

        /* Optional: Zebra striping for table rows */
        .table tbody tr:nth-child(odd) {
            background-color: #f9f9f9;
        }

        /* Center the table horizontally */
        .table-responsive {
            margin-left: auto;
            margin-right: auto;
        }

        /* Style the top row for better visibility */
        .thead-light th {
            background-color: #e0e0e0; /* Slightly darker gray background */
            font-weight: bold;
            text-align: left; /* Align text to the left */
            padding-left: 20px; /* Add left padding for better alignment */
        }
    </style>
{% endblock stylesheets %}

{% block content %}
<main class="content">
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th class="border-bottom" scope="col">CAD FILES LIST</th>
                    <th class="border-bottom" scope="col">ACTIONS</th>
                </tr>
            </thead>
            <tbody>
                {% for object in objects %}
                <tr>
                    <th class="text-gray-900" scope="row">
                        <a href="{% url 'processing_data:view_object' object.id %}">{{ object }}</a>
                    </th>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="{% url 'processing_data:download_object' object.id %}" class="btn btn-primary btn-lg">
                                <i class="fas fa-cloud-download-alt"></i>
                            </a>
                            <a href="{% url 'processing_data:edit_object' object.id %}" class="btn btn-success btn-lg">
                                <i class="fas fa-pencil-alt"></i>
                            </a>
                            <a href="{% url 'processing_data:delete_object' object.id %}" class="btn btn-danger btn-lg">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}